name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
#      docker_registry:
#        required: true
#        type: string
      docker_tag:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}" ${{ inputs.docker_registry }}

      - name: Build Docker Image
        run: docker build -t ${{ inputs.docker_registry }}/${{ inputs.image_name }}:${{ inputs.docker_tag }} .

      - name: Push Docker Image
        run: docker push ${{ inputs.docker_registry }}/${{ inputs.image_name }}:${{ inputs.docker_tag }}